# Generated by Django 3.0.8 on 2020-07-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fillform', '0003_auto_20200726_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicetree',
            name='question',
        ),
        migrations.DeleteModel(
            name='ChoiceHedge',
        ),
        migrations.DeleteModel(
            name='ChoiceTree',
        ),
        migrations.DeleteModel(
            name='QuestionHedge',
        ),
        migrations.DeleteModel(
            name='QuestionTree',
        ),
    ]
