# Generated by Django 3.0.8 on 2020-07-27 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fillform', '0004_auto_20200727_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question2_text', models.CharField(max_length=200)),
                ('last_choices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fillform.Choice')),
            ],
        ),
    ]
