# Generated by Django 3.0.8 on 2020-07-27 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fillform', '0005_question2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fillform.Question2')),
            ],
        ),
    ]
